### ISSUE TITLE
Show translations/expansion of instructions in debug view

### ISSUE THREAD

**Issue by wallento** [hm-riscv/vscode-riscv-venus#1]
The assembler of the Venus simulator supports pseudo-instructions and therefore stepping through the code means that a single assembly line can expand to multiple instructions. For example

```asm
li x1, 0x12345678
```

translates to

```asm
lui x1, 0x12345
addi x1, x1, 0x678
```

Currently the debugger would double step through it.

There are a couple of options and inspirations:

1. We could show the assembled file, similar to platform.io

![image](https://user-images.githubusercontent.com/299017/79995887-133f8400-84b8-11ea-82fe-00a61f951c9c.png)

It would have the advantage that it already easily supports linking multiple sources in a coherent view. Challenge is probably to sync it to the source code view. Maybe we can get inspired by platform.io sources :)

2. We could instead show the translated code "annotated" in the source code, similar as the CUDA IDE does:

![image](https://user-images.githubusercontent.com/299017/79996299-99f46100-84b8-11ea-9b61-977d00fa02fb.png)

I like the view, it feels more consistent. But it may be more challenging to implement.

**Comment by m1n1** [comment]
![image](https://user-images.githubusercontent.com/43846168/91053196-c6fd7f80-e622-11ea-8a98-9c900ba5bf3c.png)

This is the current implementation.
