### ISSUE TITLE
Missing `jalr` Instruction Format 

### ISSUE THREAD

**Issue by Wladefant** [hm-riscv/vscode-riscv-venus#110]
I have reported the issue directly in the simulator project, as this extension is based on it: https://github.com/61c-teach/venus/issues/5

I appreciate you. This is the only extension on the entire marketplace that offers a reliable risc v simulator.

## Environment
- Extension/Venus Simulator Version: 1.7.0
- Operating System: Windows 11
- ISA Reference: RISC-V Unprivileged ISA V20191213

## Issue Description
When using the VSCode extension based on the Venus simulator, an `AssemblerError` is thrown for using the `jalr` instruction in a displaced notation format.

### Error Message
```
AssemblerError: fix.S:39: I-Type Instructions should not be in Displaced Notation! jalr zero, 0(ra)
```

This error appears inconsistent with the GNU Assembler's acceptance of both `jalr zero,ra,0` and `jalr zero,0(ra)` syntax, as indicated in the ISA documentation and the GNU Assembler source code (https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=opcodes/riscv-opc.c;h=fcba49972f01b639072d303ace0804c900c12bfb;hb=refs/heads/master#l370).

### Expected Behavior
Both `jalr zero,ra,0` and `jalr zero,0(ra)` should be accepted by the assembler without errors, following the GNU Assembler's example and the written rule in the RISC-V ISA documentation.

### Steps to Reproduce
1. Write a RISC-V assembly program using the `jalr` instruction in the format `jalr zero, 0(ra)`.
2. Attempt to assemble the program using the VSCode extension for RISC-V based on the Venus simulator.
3. Observe the `AssemblerError` indicating that the displaced notation should not be used.

### Additional Context
Attached is an excerpt from the RISC-V ISA documentation indicating the standard `jalr` instruction usage, which seems to align with the GNU Assembler's flexibility. This discrepancy between the ISA and the Venus simulator's interpretation could lead to confusion and potential errors in assembly programs.

![RISC-V ISA excerpt](https://github.com/hm-riscv/vscode-riscv-venus/assets/79611093/3ee22a0d-7109-4f44-92ff-9db16d155c2f)

**Comment by wallento** [comment]
Thanks a lot for reporting. This is indeed an annoying issue with the simulator that we actually pull in from the external Venus project. But it is also a good trigger to get it solved there, which I will take care of and then update the change here.

**Comment by Wladefant** [comment]
Nice thank you for the fast answer: I reported it there it too as it made more sense there. https://github.com/61c-teach/venus/issues/5

**Comment by Wladefant** [comment]
And thank you for merging the breakpoint fix for windows. Would be nice if you could push it to the extension store too

**Comment by wallento** [comment]
Yes, I am working on that right now

**Comment by wallento** [comment]
Can you please tryout this pre-release: https://github.com/hm-riscv/vscode-riscv-venus/releases/tag/v1.7.5-0

**Comment by Wladefant** [comment]
Yes works, thank you
