### ISSUE TITLE
Finalize ECall interface

### ISSUE THREAD

**Issue by m1n1** [hm-riscv/vscode-riscv-venus#12]
This are the possible implementations that we discussed:

- LookupTable with Function Pointer in Kotlin. From VSCode functions can be added to the LookupTable. Prefered for now.

- EventEmitter. Problem: Async?

- declare extern Funktion in Kotlin and implement it in VSCode. Not very flexible and declaring extern functions in Kotlin feels not very safe.

**Comment by m1n1** [comment]
The current Solution is:

- An Function which expects a json-string can be registered via a function in venus
- Every time a ecall is happening a json is constructed and send to that receiver function
- The receiver can extract the information and react arcodingly. The function returns syncronous.

The solution with json was chosen because only one receiver function is needed. This makes the setup and communication much simpler. Also it is a more generic approach. 

In the future maybe a solution which sends json via WebSockets will be implemented. WebSocket support has been added recently in the venusbackend and that could be used.

**Comment by wallento** [comment]
Just some minor remarks and discussion points:
- Will the called function be able to access the CPU/memory state?
- We should have a range of ecalls directed to this function and have everything handled there

**Comment by wallento** [comment]
I think this looks good now. From my point of view missing are:

- [ ] Returning json with a0-a7 updates
- [ ] Provide access to memory via json

**Comment by wallento** [comment]
Then we can upstream it I believe

**Comment by wallento** [comment]
Memory can be accessed from the simulator directly, see memory view
