### ISSUE TITLE
git submodule for venus backend

### ISSUE THREAD

**Issue by wallento** [hm-riscv/vscode-riscv-venus#5]
Instead of adding the source files, we should use the venus backend as git submodule and generate the js during build

**Comment by haerrel** [comment]
Need admin access rights to [venus repo](https://github.com/hm-riscv/venus) to migrate repo from gitlab

**Comment by haerrel** [comment]
254de9dd12f8155a164359a3eb9b0927b6d50541: build venus when releasing extension
ef182534ee0679db93a7cde94ecfbf8228ab7681: build venus when publishing extension (fails atm, this is a other issue though)
