### ISSUE TITLE
Problem with macOS - scratch directory issue

### ISSUE THREAD

**Issue by U2654** [hm-riscv/vscode-riscv-venus#50]
Does not work properly with macOS. I tracked down the problem to the generation of the scratch directory in riscvSimulator.ts, line 19:
	global["localStorage"] = new LocalStorage('./scratch');

Under Linux, the correct path will generated in LocalStorage. MacOS gives /scratch which is not correct. You could fix the problem by, e.g.
    global["localStorage"] = new LocalStorage(__dirname + '/scratch');

Or you might have a better solution.

**Comment by m1n1** [comment]
Thanks for reporting. Unfortunately me and my colleagues don't have a Mac so any feedback regarding macOS is highly appreciated!

The fix for this issue will be (most likely) included in the next release. I will post updates here.

**Comment by U2654** [comment]
Thanks. Just inform me when you release. I will check very soon and report here.

**Comment by m1n1** [comment]
Hi,  @U2654  in the newest version 1.4.6 this should be fixed. We already got positive feedback from our students but I would also like your opinion.

**Comment by U2654** [comment]
Yes. I can confirm this. Great! Thanks.
