### ISSUE TITLE
Make registers mutable

### ISSUE THREAD

**Issue by wallento** [hm-riscv/vscode-riscv-venus#9]
As suggested by @ThaumicMekanism, we should make it possible to change a register value in the register view. Probably as text that changes to a text field when clicked, maybe best adopted from other debug views. Loosely relates to #2

**Comment by m1n1** [comment]
I added this feature for the int registers. Just double click the value in the variables/registers panel on the left of the debugger. Then you can enter your value as decimal or hexadecimal (maybe add binary support?). 

I'm unsure however how to overwrite float registers, or better said in what format the float registers values are saved. Would it even be usable for a user to change the values of fregisters directly?

**Comment by m1n1** [comment]
This now also works for float registers.

The current solution seems stable.
